# Site Info
title:        Sanggil Log # 블로그 제목
tagline:      'Log for Develop' # 페이지 제목 옆에 나타나는 설명 글
description:  '소소한 일상의 기록' # 블로그 설명
baseurl:      ''
url:          https://sanggil1107.github.io/
logo:         '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate-v2
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 10
paginate_path: "page:num"

permalink: /:year/:month/:title.html
plugins:
  - jekyll-paginate-v2
# Custom vars
version: 1.0.0

# About/contact
author:
  name: Sanggil Yang
  description: '개발을 즐기는 초보 개발자' # 저자 설명
#  gravatar: 78abf09c8af4042796ff9379143da32f # md5 hash of your email address
  contact:
    #linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/sanggil1107
    # facebook:  <hide>
    #twitter:   https://twitter.com/Li_Zhihao
    #weibo:     http://weibo.com/41173780
    email:    yangpang1107@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  ABOUT:
  CATEGORY:
    - '/blog/'
    - { Programming: '/blog/categories/' }
    - { Cloud: '/blog/categories/' }
    - { Blog: '/blog/categories/' }


# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-67856795-3' # leave blank if you don't want google analytics
disqus_short_name: 'ringsterz' # leave blank if you don't want disqus

theme_settings:
  str_next_page: "Next"
  str_previous_page: "Prev"
  post_navigation: true

excerpt_separator: <!--more-->